### ISSUE TITLE
A question...(URGENT HELP)

### ISSUE THREAD

**Issue by Yush-12** [Voldemort271/enlightenment-bibliotheca#1]
Hello Shubham, well I don't know if this is supposed to go into issues but i am a newbie and cant find another way to contact you right now so here I am. Well as stated before I am a newbie and I am in 12th standard right now and as I am nearing the end of my academic year we are given school projects and I am a student of computer science and have gotten a project on Library Management System and i am fairly new to python and MySQL well really new so with no prior knowledge I went on google and after research found your project ton GitHub it really fascinated me and I kind of used it and made changes from my side well i hope you don't mind but I will be sure to credit you in the bibliography... Now I am stuck at a point I have to add a Delete Books Module/function part in the program, by far I was only able to add the Button of it in there so now after being able to do nothing I am here trying to get help from you I would be really grateful if you helped me with the code for deleting books from the database and all the stuff on your project...

I don't know if you will read this message or not but if you do please message me back and if you have any other form of contact you are comfortable in i will be willing to imply so to talk things out there...

Best Regards,
YushPlayz
(Aayush)

**Comment by Voldemort271** [comment]
Hey Aayush, well this definitely isnt supposed to go here but thats ok lol, its my bad that i didnt open a Discussions here. There's no problem being fairly new, i came to know that mySQL exists right when our teacher taught it xD i'm kind of an unruly student, but thats a topic for another day. 
Coming to your question, if you want to make a page by which you want to delete books, think about what input you need — afaik only the book name. You can pass those names (by ways of which I have used in the "issue books" page), and when the user selects a book and clicks on the Submit button (be sure to double-triple-check tho), you can use the query:

`delete from <table-name> where id = <book-id>;`

That being said, I probably didnt add a delete books option because (I'm lazy) logically speaking, deleting books off of a library is not a think that just anyone can do lol, theres authorised people that do it. So I initially had the idea of making a login page after which users would have access to the delete page too, but this project had already trampled well over 2000 lines — keep in mind that at my school, anything over 500 lines was unheard of — so i had to cut it out. Maybe when I'll have the time I'll make it, but this project isnt reaching a wide audience anyway ;-;

Hope I cleared your query (if not then please be specific), and feel free to contact me in the Discussions here; I'll open one. In case I forget, I'll have one waiting in my github.io page, cheers!
